USE [APOTHIKI_4268]
GO
SET IDENTITY_INSERT [dbo].[APOTHIKI] ON 

INSERT [dbo].[APOTHIKI] ([KE], [EIDOS], [KATHGORIA], [APOTHEMA], [TIMH_POLHSHS], [FPA]) VALUES (1, N'йаята цяажийым', N'тевмокоциа', 20, 150.0000, 0.24)
INSERT [dbo].[APOTHIKI] ([KE], [EIDOS], [KATHGORIA], [APOTHEMA], [TIMH_POLHSHS], [FPA]) VALUES (2, N'епенеяцастгс', N'тевмокоциа', 40, 220.0000, 0.24)
INSERT [dbo].[APOTHIKI] ([KE], [EIDOS], [KATHGORIA], [APOTHEMA], [TIMH_POLHSHS], [FPA]) VALUES (3, N'тяожодотийо', N'тевмокоциа', 20, 40.0000, 0.24)
SET IDENTITY_INSERT [dbo].[APOTHIKI] OFF
SET IDENTITY_INSERT [dbo].[PELATHS] ON 

INSERT [dbo].[PELATHS] ([KOD_PELATH], [EPONYMIA], [EPITHETO], [ONOMA], [HM_GENHSHS], [HLIKIA], [AFM], [DOY], [DIEYTHINSI], [POLH], [THL], [FOTO], [SXOLIA]) VALUES (1, N'лафмгс а.е', N'лафмгс', N'ахамасиос', CAST(N'1998-11-16T00:00:00' AS SmallDateTime), 20, N'1234', N'12345', N'ациа паяасйеуг 12', N'хессакомийг', N'2396041444', NULL, NULL)
INSERT [dbo].[PELATHS] ([KOD_PELATH], [EPONYMIA], [EPITHETO], [ONOMA], [HM_GENHSHS], [HLIKIA], [AFM], [DOY], [DIEYTHINSI], [POLH], [THL], [FOTO], [SXOLIA]) VALUES (2, N'фоялпас а.е', N'фоялпас', N'мийос', CAST(N'1998-01-12T00:00:00' AS SmallDateTime), 21, N'4567', N'45678', N'тяапефоумтос', N'сеяяес', N'2321065652', NULL, NULL)
INSERT [dbo].[PELATHS] ([KOD_PELATH], [EPONYMIA], [EPITHETO], [ONOMA], [HM_GENHSHS], [HLIKIA], [AFM], [DOY], [DIEYTHINSI], [POLH], [THL], [FOTO], [SXOLIA]) VALUES (3, N'сулеымидгс а.е', N'сулеымидгс', N'саббас', CAST(N'1997-05-25T00:00:00' AS SmallDateTime), 22, N'7890', N'78910', N'хессакомийгс 30', N'хессакомийг', N'2310454532', NULL, NULL)
INSERT [dbo].[PELATHS] ([KOD_PELATH], [EPONYMIA], [EPITHETO], [ONOMA], [HM_GENHSHS], [HLIKIA], [AFM], [DOY], [DIEYTHINSI], [POLH], [THL], [FOTO], [SXOLIA]) VALUES (4, N'йаяаходыягс', N'йаяаходыягс', N'мийос', CAST(N'1980-03-21T00:00:00' AS SmallDateTime), 39, N'1514', N'15143', N'йуьекг', N'ахгма', N'2106565842', NULL, NULL)
SET IDENTITY_INSERT [dbo].[PELATHS] OFF
SET IDENTITY_INSERT [dbo].[PARAGELIA] ON 

INSERT [dbo].[PARAGELIA] ([KOD_PAR], [HMER_PARAGELIAS], [K_PEL], [TROPOS_PLHROMHS], [TOPOS_PARADOSHS]) VALUES (1, CAST(N'2019-01-01T00:00:06.670' AS DateTime), 1, N'амтийатабокг', N'хессакомийг')
INSERT [dbo].[PARAGELIA] ([KOD_PAR], [HMER_PARAGELIAS], [K_PEL], [TROPOS_PLHROMHS], [TOPOS_PARADOSHS]) VALUES (2, CAST(N'2019-03-03T00:00:06.673' AS DateTime), 2, N'досеис', N'сеяяес')
INSERT [dbo].[PARAGELIA] ([KOD_PAR], [HMER_PARAGELIAS], [K_PEL], [TROPOS_PLHROMHS], [TOPOS_PARADOSHS]) VALUES (3, CAST(N'2019-04-05T00:00:06.677' AS DateTime), 3, N'йатахесг', N'хессакомийг')
SET IDENTITY_INSERT [dbo].[PARAGELIA] OFF
INSERT [dbo].[PROIONTA_PARAGELIAS] ([K_PAR], [K_E], [POSOTHTA]) VALUES (1, 1, 1)
INSERT [dbo].[PROIONTA_PARAGELIAS] ([K_PAR], [K_E], [POSOTHTA]) VALUES (2, 1, 2)
INSERT [dbo].[PROIONTA_PARAGELIAS] ([K_PAR], [K_E], [POSOTHTA]) VALUES (3, 2, 2)
INSERT [dbo].[PROIONTA_PARAGELIAS] ([K_PAR], [K_E], [POSOTHTA]) VALUES (3, 3, 2)