CREATE TABLE PARAGELIA(
	KOD_PAR INT NOT NULL,
	HMER_PARAGELIAS SMALLDATETIME,
	K_PEL INT,
	TROPOS_PLHROMHS VARCHAR(50),
	TOPOS_PLHROMHS VARCHAR(50),
	CONSTRAINT FK_PARAGELIA PRIMARY KEY(KOD_PAR));