CREATE TABLE PELATHS(
	KOD_PELATH INT NOT NULL,
	EPONYMIA VARCHAR(50),
	EPITHETO VARCHAR(50),
	ONOMA VARCHAR(50),
	HM_GENHSHS SMALLDATETIME,
	HLIKIA INT,
	AFM VARCHAR(50),
	DOY VARCHAR(50),
	DIEYTHINSI VARCHAR(50),
	POLH VARCHAR(50),
	THL VARCHAR(50),
	FOTO VARCHAR(50),
	SXOLIA VARCHAR(50),
	CONSTRAINT FK_PELATH PRIMARY KEY(KOD_PELATH));


